woowa-techcamp-2022/android-banchan-06

build.gradle, presentation/build.gradle, presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/woowahan/banchan/application/BanchanOrderApplication.kt, presentation/src/main/java/com/woowahan/banchan/di/AppModule.kt, presentation/src/main/java/com/woowahan/banchan/di/RetrofitModule.kt
=> [Feature] Presentation 모듈에 Retrofit Module 작성

data/build.gradle, data/src/main/java/com/woowahan/data/entity/BanchanDetailEntity.kt, data/src/main/java/com/woowahan/data/entity/BanchanEntity.kt, data/src/main/java/com/woowahan/data/entity/ContestBanchanEntity.kt, data/src/main/java/com/woowahan/data/entity/MainDishBanchanEntity.kt, data/src/main/java/com/woowahan/data/entity/SideDishBanchanEntity.kt, data/src/main/java/com/woowahan/data/entity/SoupDishBanchanEntity.kt
=> [Feature] 반찬 주문앱 Api 들의 Entity

presentation/build.gradle, presentation/src/main/java/com/woowahan/banchan/LifeCycleLogObserver.kt, presentation/src/main/java/com/woowahan/banchan/application/BanchanOrderApplication.kt, presentation/src/main/java/com/woowahan/banchan/ui/base/BaseActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/base/BaseFragment.kt, presentation/src/main/java/com/woowahan/banchan/util/AppCompatExtension.kt, presentation/src/main/java/com/woowahan/banchan/util/FragmentExtension.kt
=> [Feature] Presentation 모듈에 Base Activity, Base Fragment 생성

data/build.gradle, data/src/main/java/com/woowahan/data/apiservice/BanchanDetailApiService.kt, data/src/main/java/com/woowahan/data/apiservice/BestBanchanApiService.kt, data/src/main/java/com/woowahan/data/apiservice/MainDishBanchanApiService.kt, data/src/main/java/com/woowahan/data/apiservice/SideBanchanApiService.kt, data/src/main/java/com/woowahan/data/apiservice/SideDishBanchanApiService.kt, data/src/main/java/com/woowahan/data/apiservice/SoupDishBanchanApiService.kt, data/src/main/java/com/woowahan/data/datasource/BanchanDetailDataSource.kt, data/src/main/java/com/woowahan/data/datasource/BanchanDetailDataSourceImpl.kt, data/src/main/java/com/woowahan/data/datasource/BanchansDataSource.kt, data/src/main/java/com/woowahan/data/datasource/BanchansRetrofitDataSourceImpl.kt, data/src/main/java/com/woowahan/data/entity/BestBanchanEntity.kt, data/src/main/java/com/woowahan/data/util/RetrofitResponseConvertUtil.kt, presentation/src/main/java/com/woowahan/banchan/di/ApiServiceModule.kt, presentation/src/main/java/com/woowahan/banchan/di/AppModule.kt
=> [Feature] Data 모듈에 Api Service, DataSource 정의

domain/src/main/java/com/woowahan/domain/MyClass.kt, domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt, domain/src/main/java/com/woowahan/domain/model/BestBanchanModel.kt, domain/src/main/java/com/woowahan/domain/repository/BanchanRepository.kt, domain/src/main/java/com/woowahan/domain/usecase/FetchBestBanchanUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/FetchMainDishBanchanUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/FetchSideDishBanchanUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/FetchSoupDishBanchanUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/FilterBanchanUseCase.kt
=> [Feature] Domain 모듈에 banchan data model class, Repository UseCase 추가

data/build.gradle, data/src/main/java/com/woowahan/data/entity/BanchanEntity.kt, data/src/main/java/com/woowahan/data/entity/BestBanchanEntity.kt, data/src/main/java/com/woowahan/data/repository/BanchanRepositoryImpl.kt, data/src/main/java/com/woowahan/data/util/RetrofitResponseConvertUtil.kt, domain/build.gradle, presentation/src/main/java/com/woowahan/banchan/di/AppModule.kt, presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt, presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
=> [Feature] BanchanRepositoryImpl 구현 

presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/util/LifeCyclerOwnerExtension.kt
- #25 
- [ X ]  ViewModel의 LiveData를 Flow 사용으로 변경
close #25
=> [Refactor] ViewModel의 LiveData를 Flow 사용으로 변경

presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/res/layout/fragment_main_dish_banchan.xml
- #24 
- [ X ] ViewModel에 UIEvent sealed class를 생성하여 Event들을 통합 관리
close #24
=> [Refactor] ViewModel에 UIEvent sealed class를 생성하여 Event들을 통합 관리

presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/root/RootTabPagerAdapter.kt, presentation/src/main/res/layout/activity_main.xml
=> [Rename] MainActivity #31

presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt, presentation/src/main/res/layout/fragment_soup_dish_banchan.xml, presentation/src/main/res/layout/item_count_header.xml
=> [Feature] 국물 요리 구현 #23

data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt, data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt, data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt, domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt, domain/src/main/java/com/woowahan/domain/usecase/GetCartItemsSizeFlowUseCase.kt, presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt, presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RootViewModel.kt
=> [Feature] 장바구니 DataSource에서 지속적으로 관찰 가능한 Flow형태를 RootActivity에서 관찰 가능한지 검토

presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
=> [Fix] 국물요리, 밑반찬 종종 바로 안 뜨는 오류

presentation/src/main/java/com/woowahan/banchan/extension/AppCompatExtension.kt, presentation/src/main/java/com/woowahan/banchan/extension/FragmentExtension.kt, presentation/src/main/java/com/woowahan/banchan/extension/IntExtension.kt, presentation/src/main/java/com/woowahan/banchan/extension/LifeCyclerOwnerExtension.kt, presentation/src/main/java/com/woowahan/banchan/extension/List<BanchanModel>Extension.kt, presentation/src/main/java/com/woowahan/banchan/extension/LongExtension.kt, presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt, presentation/src/main/java/com/woowahan/banchan/ui/dialog/MainDialog.kt, presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/util/DialogUtil.kt, presentation/src/main/res/drawable/bg_main_dialog.xml, presentation/src/main/res/layout/dialog_main.xml, presentation/src/main/res/values/dimen.xml
=> [Feature] 반찬주문앱 Dialog 제작

presentation/src/main/java/com/woowahan/banchan/ui/adapter/decoratin/GridItemDecoration.kt, presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
- #55 
-[x] Extension 파일들의 패키지 이동으로 인한 kotlin file들의 import 문제 수정
close #55
=> [Fix] #55 Extension 파일들의 패키지 이동으로 인한 kotlin file들의 import 문제 수정

presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/res/layout/item_menu_horizontal.xml
=> [Fix] Grid item 여백 오류

presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt, presentation/src/main/res/layout/item_badge_cart.xml
=> [fix] app bar 장바구니 아이콘 클릭 안되는 문제

presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
=> [Feature] 장바구니 추가, 제거시 Dialog 표시 

data/src/main/java/com/woowahan/data/repository/BanchanDetailRepositoryImpl.kt, data/src/main/java/com/woowahan/data/repository/BanchanRepositoryImpl.kt, domain/src/main/java/com/woowahan/domain/repository/BanchanDetailRepository.kt, domain/src/main/java/com/woowahan/domain/repository/BanchanRepository.kt, domain/src/main/java/com/woowahan/domain/usecase/FetchBestBanchanUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/FetchMainDishBanchanUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/FetchSideDishBanchanUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/FetchSoupDishBanchanUseCase.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
=> [Refactor] Banchan Repository, UseCase의 비동기처리를 Flow를 사용하여 구현 검토, 적용

data/src/main/java/com/woowahan/data/dao/CartDao.kt, data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt, data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt, data/src/main/java/com/woowahan/data/entity/dto/CartDto.kt, data/src/main/java/com/woowahan/data/entity/table/CartTableEntity.kt, data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt, domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt, domain/src/main/java/com/woowahan/domain/usecase/UpdateCartItemCountUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/UpdateCartItemSelectUseCase.kt, presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
=> [Feature] Cart Table Entity 에 select 속성 추가

presentation/src/main/java/com/woowahan/banchan/ui/adapter/ViewModeToggleBanchanAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
=> [fix] View Mode Toggle, Filter 버그 수정

domain/src/main/java/com/woowahan/domain/usecase/FetchBestBanchanUseCase.kt, presentation/src/main/java/com/woowahan/banchan/extension/List<BestBanchan>Extension.kt, presentation/src/main/java/com/woowahan/banchan/extension/RecyclerViewExtension.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/BestBanchanAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/HorizontalBanchanListAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/BanchanListBannerViewHolder.kt, presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt, presentation/src/main/res/layout/fragment_best_banchan.xml, presentation/src/main/res/layout/item_bachan_list_banner.xml, presentation/src/main/res/layout/item_menu_best_horizontal_child.xml, presentation/src/main/res/layout/item_menu_horizontal_list.xml, presentation/src/main/res/values/strings.xml
=> [Feature] 기획전 화면 구현

presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
=> [fix] MainDishFragment의 ItemDecorator 중첩 문제 해결

presentation/src/main/java/com/woowahan/banchan/bindingadapter/TextViewBindingAdapter.kt, presentation/src/main/res/layout/dialog_cart_add.xml, presentation/src/main/res/layout/item_menu_best_horizontal_child.xml, presentation/src/main/res/layout/item_menu_horizontal.xml, presentation/src/main/res/layout/item_menu_vertical.xml
=> [Design] 할인가가 존재한다면, 정가 text 취소선 처리

presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt, presentation/src/main/res/layout/activity_recent_viewed.xml, presentation/src/main/res/layout/item_menu_time_stamp.xml
=> [Design] 최근 본 상품 목록에 취소선 적용

presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
=> [Feature] 기획전 화면에 장바구니 화면 연동

presentation/src/main/res/layout/item_cart_content.xml
=> [Design] Cart button ripple 적용

data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt, data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt, data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt, data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt, domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt, domain/src/main/java/com/woowahan/domain/model/BaseBanchan.kt, domain/src/main/java/com/woowahan/domain/model/RecentViewedItemModel.kt, domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt, domain/src/main/java/com/woowahan/domain/usecase/cart/InsertCartItemUseCase.kt, presentation/src/main/java/com/woowahan/banchan/extension/List<BanchanModel>Extension.kt, presentation/src/main/java/com/woowahan/banchan/extension/List<BestBanchan>Extension.kt, presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt, presentation/src/main/res/layout/dialog_cart_add.xml
=> [Refactor] Banchan, Recent Item의 Base Model 작성

data/src/main/java/com/woowahan/data/dao/BanchanDao.kt, data/src/main/java/com/woowahan/data/dao/CartDao.kt, data/src/main/java/com/woowahan/data/dao/RecentViewedDao.kt, data/src/main/java/com/woowahan/data/database/BanchanRoomDatabase.kt, data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt, data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSourceImpl.kt, data/src/main/java/com/woowahan/data/entity/table/RecentViewedTableEntity.kt, domain/src/main/java/com/woowahan/domain/model/RecentViewedItemModel.kt, presentation/src/main/java/com/woowahan/banchan/RecentViewedModelDiffUtilCallback.kt, presentation/src/main/java/com/woowahan/banchan/bindingadapter/TextViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/banchan/di/DaoModule.kt, presentation/src/main/java/com/woowahan/banchan/extension/DateExtension.kt, presentation/src/main/java/com/woowahan/banchan/extension/List<RecentViewedItemModel>Extension.kt, presentation/src/main/java/com/woowahan/banchan/extension/List<RecentViewedModel>Extension.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt, presentation/src/main/res/layout/item_menu_time_stamp.xml
=> [Feature] 최근 본 목록 View와 Room 연동

domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt, presentation/src/main/java/com/woowahan/banchan/CartListModelDiffUtilCallback.kt
=> [Fix] Cart Payload 수정

data/src/main/java/com/woowahan/data/dao/OrderDao.kt, data/src/main/java/com/woowahan/data/database/BanchanRoomDatabase.kt, data/src/main/java/com/woowahan/data/datasource/OrderDataSource.kt, data/src/main/java/com/woowahan/data/datasource/OrderDataSourceImpl.kt, data/src/main/java/com/woowahan/data/entity/dto/OrderDto.kt, data/src/main/java/com/woowahan/data/entity/table/OrderItemTableEntity.kt, data/src/main/java/com/woowahan/data/entity/table/OrderTableEntity.kt, data/src/main/java/com/woowahan/data/repository/OrderRepositoryImpl.kt, domain/src/main/java/com/woowahan/domain/model/OrderModel.kt, domain/src/main/java/com/woowahan/domain/repository/OrderRepository.kt, domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrdersUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/order/GetDeliveryOrderCountUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/order/InsertOrderUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/order/UpdateOrderUseCase.kt, presentation/src/main/java/com/woowahan/banchan/di/DaoModule.kt, presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt, presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt, presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt, presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RootViewModel.kt
=> [Feature] 주문하기 기능 Data, Domain 모듈 작성

presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
=> [Fix] Cart Payload 수정 

domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt, presentation/src/main/java/com/woowahan/banchan/CartListModelDiffUtilCallback.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt, presentation/src/main/res/layout/item_cart_content.xml, presentation/src/main/res/layout/item_cart_footer.xml
=> [Feature] Cart payload 구현

data/src/main/java/com/woowahan/data/dao/OrderDao.kt, domain/src/main/java/com/woowahan/domain/model/OrderModel.kt, domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt, presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderItemViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderListViewModel.kt, presentation/src/main/res/drawable/ic_arrow_right_black.xml, presentation/src/main/res/drawable/ic_refresh.xml, presentation/src/main/res/layout/activity_order_item.xml, presentation/src/main/res/layout/activity_order_list.xml, presentation/src/main/res/layout/item_order_horizontal.xml, presentation/src/main/res/layout/item_order_list.xml, presentation/src/main/res/layout/item_order_state_footer.xml, presentation/src/main/res/layout/item_order_state_header.xml, presentation/src/main/res/menu/menu_order_item.xml, presentation/src/main/res/values/colors.xml, presentation/src/main/res/values/strings.xml
=> [Feature] 주문하기 Presentation 모듈 작성

data/src/main/java/com/woowahan/data/entity/BanchanDetailEntity.kt, data/src/main/java/com/woowahan/data/repository/BanchanDetailRepositoryImpl.kt, domain/src/main/java/com/woowahan/domain/constant/DeliveryConstant.kt, domain/src/main/java/com/woowahan/domain/model/BanchanDetailModel.kt, domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt, domain/src/main/java/com/woowahan/domain/model/OrderModel.kt, domain/src/main/java/com/woowahan/domain/usecase/cart/FetchCartItemsUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
=> [Refactor] Delivery constant 적용

domain/src/main/java/com/woowahan/domain/model/OrderModel.kt, domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt, presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemAdapter.kt
=> [Fix] Order Item 화면에서, Footer에 가격 적용 안되고 있는 문제 수정

domain/src/main/java/com/woowahan/domain/model/ApiServiceThrowable.kt, presentation/src/main/java/com/woowahan/banchan/di/RetrofitModule.kt, presentation/src/main/java/com/woowahan/banchan/extension/AppCompatExtension.kt, presentation/src/main/java/com/woowahan/banchan/network/NetworkConnectionInterceptor.kt, presentation/src/main/java/com/woowahan/banchan/ui/base/BaseNetworkActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/detail/BanchanDetailActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt, presentation/src/main/res/layout/activity_main.xml, presentation/src/main/res/values/strings.xml
=> [Feature] 네트워크 상태 처리

presentation/src/main/java/com/woowahan/banchan/background/DeliveryRequester.kt, presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderItemViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderListViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt, presentation/src/main/res/layout/activity_cart.xml, presentation/src/main/res/layout/activity_order_list.xml, presentation/src/main/res/layout/activity_recent_viewed.xml, presentation/src/main/res/layout/fragment_best_banchan.xml, presentation/src/main/res/layout/fragment_main_dish_banchan.xml, presentation/src/main/res/layout/fragment_side_dish_banchan.xml, presentation/src/main/res/layout/fragment_soup_dish_banchan.xml
=> [Fix] ViewModel Flow 수정

data/src/test/java/com/woowahan/data/datasource/BanchansRetrofitDataSourceImplTest.kt
=> [Test] Banchan DataSource 테스트 코드 수정

presentation/src/main/java/com/woowahan/banchan/ui/base/BaseNetworkActivity.kt, presentation/src/main/res/layout/activity_cart.xml
=> [Fix] 화면 진입시마다 네트워크 안내가 표시되는 문제 수정

data/src/main/java/com/woowahan/data/datasource/BanchanDetailCacheDataSource.kt, data/src/main/java/com/woowahan/data/datasource/BanchanDetailCacheDataSourceImpl.kt, data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt, data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt, presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt, presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
=> [Feature] Banchan Detail Cache DataSource 생성, 적용

build.gradle, presentation/build.gradle
=> [Feature] Firebase Crashlytics 플러그인 추가

presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
=> [Fix] 장바구니 삭제 후 최근 본 목록화면에서 재등록 시 주문하기 안보임

presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt, presentation/src/main/res/layout/item_cart_content.xml
=> [Fix] 장바구니 수량 조절 안 먹히는 버그 수정 

presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
=> [Fix] payload 여러개 처리 에러

presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/CountHeaderViewHolder.kt
=> [Bug] 밑반찬, 국물요리 총 아이템 수 버그

presentation/src/main/java/com/woowahan/banchan/ui/detail/BanchanDetailActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/DetailViewModel.kt, presentation/src/main/java/com/woowahan/banchan/util/DialogUtil.kt
=> [Feature] Banchan Detail 화면에서 에러 발생시 처리

.gitignore, presentation/build.gradle, presentation/src/main/java/com/woowahan/banchan/background/DeliveryRequester.kt
=> [Release] 1.0.1 배포 준비

presentation/release/output-metadata.json, presentation/src/main/java/com/woowahan/banchan/bindingadapter/EditTextBindingAdapter.kt
=> [Bug] 장바구니에서 수량 0개로 입력한 상황 핸들링 필요

data/src/main/java/com/woowahan/data/dao/OrderDao.kt, data/src/main/java/com/woowahan/data/datasource/OrderDataSource.kt, data/src/main/java/com/woowahan/data/datasource/OrderDataSourceImpl.kt, data/src/main/java/com/woowahan/data/repository/OrderRepositoryImpl.kt, domain/src/main/java/com/woowahan/domain/repository/OrderRepository.kt, domain/src/main/java/com/woowahan/domain/usecase/order/UpdateMissingDeliveryOrderUseCase.kt, domain/src/main/java/com/woowahan/domain/usecase/order/UpdateOrderUseCase.kt, presentation/src/main/java/com/woowahan/banchan/background/DeliveryAlarmReceiver.kt, presentation/src/main/java/com/woowahan/banchan/background/DeliveryWorker.kt, presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RootViewModel.kt
=> [Bug] 디바이스 재부팅시 주문 상태가 업데이트 되지 않음

domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BaseCartUpdateViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
- #183 
- #191 
close #183 
close #191
=> [Bug] 메인화면 탭 Spinner Filter 버그 수정

presentation/src/main/java/com/woowahan/banchan/background/DeliveryRequester.kt, presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemAdapter.kt, presentation/src/main/res/layout/item_order_list.xml
=> [Bug] OrderList, Order화면 수정

presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt, presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
=> [Bug] 빠르게 장바구니 아이콘 클릭시 바텀 시트 여러개 뜸

domain/src/main/java/com/woowahan/domain/model/BaseBanchan.kt, presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt, presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt, presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartItemInsertBottomSheetViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt, presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt, presentation/src/main/res/layout/dialog_cart_add.xml
- #185 
- #187
- 수정사항이 겹치는 부분이 있어서 함께 언급
close #185
close #187
=> [Bug] 바텀 다이얼로그 보여진채로 회전시 crash

presentation/src/main/AndroidManifest.xml
=> [Bug] 장바구니에서 화면 회전시 crash

presentation/build.gradle
=> [Release] 1.0.2

presentation/build.gradle
=> [Release] 1.0.3 

presentation/src/main/java/com/woowahan/banchan/ui/adapter/BestBanchanAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/HorizontalBanchanListAdapter.kt, presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedHorizontalAdapter.kt
=> [Modify] ViewHolder가 RecyclerView를 가지고있을때, updateList에 대해 확인
